name: golang_ci
on: [push]
jobs:
  build:
    name: all
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: go test ./... -v
